name: githubchart

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: githubchart
    steps:
      - uses: actions/checkout@v3
      - uses: Benbentwo/githubchart@0.1.0
        with:
          username: hosseinabbasi-toast
          file-output: assets/images/contribution.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "githubchart generated"
          git push
