name: Create-GitHub-User-Contribution-Chart

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: github-action-user-contribution
    steps:
      - uses: actions/checkout@v3
      - uses: alexrogalskiy/github-action-user-contribution@master
        with:
          userName: 'hosseinabbasi-toast'
          colorScheme: 'green'
          fileName: 'chart.svg'
          filePath: 'images'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Create-GitHub-User-Contribution-Chart generated"
          git push
